name: 'Issue'
description: '새로 생성된 이슈는 Jira와 연동돼요'
title: 'Issue 제목을 작성해주세요'
body:
  - type: input
    id: parentKey
    attributes:
      label: 'Ticket Number'
      description: '상위 작업의 Ticket Number를 기입해주세요'
      placeholder: 'LCO-00'
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: 'Description'
      description: '이슈에 대해 간략히 설명해주세요'
    validations:
      required: true

  - type: dropdown
    id: issueLabel
    attributes:
      label: 'Label'
      description: '이슈의 라벨을 선택해주세요'
      multiple: true
      options:
        - Feature
        - Fix
        - DOCS
        - Refactor
        - Setting
    validations:
      required: true

  - type: textarea
    id: tasks
    attributes:
      label: 'Tasks'
      description: '이슈에 대한 필요한 작업 목록을 작성해주세요'
      value: |
        - [ ]
        - [ ]
        - [ ]
    validations:
      required: true
