name: Synchronize to forked repo
on:
  push:
    branches:
      - main
      - develop

jobs:
  sync:
    name: Sync forked repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.AUTO_ACTIONS }}
          fetch-depth: 0
          ref: ${{ github.ref_name }} 

      - name: Add remote-url
        run: |
          git remote add forked-repo https://heeyyeon:${{ secrets.AUTO_ACTIONS }}@github.com/heeyyeon/LOCOCO-CLIENT
          git config user.name heeyyeon
          git config user.email ${{ secrets.EMAIL }}

      - name: Push changes to forked-repo
        run: |
          git push -f forked-repo ${{ github.ref_name }}

      - name: Clean up
        run: |
          git remote remove forked-repo
